# docker-compose.yml
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ece9065
      POSTGRES_PASSWORD: uwo
      TZ: America/Toronto
    ports:
      - 5432:5432
    restart: on-failure:3
    volumes:
      - postgres:/var/lib/postgresql/data
  pgweb:
    image: sosedoff/pgweb
    depends_on:
      - postgres
    environment:
      PGWEB_DATABASE_URL: postgres://ece9065:uwo@postgres:5432/ecommerce?sslmode=disable
      TZ: America/Toronto
      PGTZ: America/Toronto
    ports:
      - 8081:8081
    restart: on-failure:3
  redis:
    image: redis:alpine
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    environment:
      TZ: America/Toronto
    ports:
      - 6379:6379
    networks:
      - redis-network
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=root
      - TZ=America/Toronto
    ports:
      - 8082:8081
    networks:
      - redis-network
    depends_on:
      - redis
volumes:
  postgres:
  redis:
  redis-config:
networks:
  redis-network:
    driver: bridge